== Introduction
Spring's Getting Started Guides are written in AsciiDoc with a common set of "macros". These macros are simply bits of
asciidoc that get included like any other source code.

This approach may sound a little funky (and it is), but it's way better than the misery of Git submodules. In fact, 
it's actually pretty easy. If you're just getting started, then follow the directions immediately below. If you're 
needing a refresher on how to keep things up to date, then head to the section at the bottom on "keeping up to date".

== Getting started with AsciiDoc
If you are using homebrew, enter the following:

[source]
brew install asciidoc source-highlighter

For other platforms, you will have to investigate similar installation tools.

=== Add the getting-started-base remote
[source]
git remote add getting-started-base https://github.com/gregturn/getting-started-base.git

=== Pull in the base infrastructure
[source]
git pull getting-started-based master

== Edit README.asciidoc
Make all your edits to the guide. To pull in macros, simply use AsciiDoc's `include` macro, like this:

[source]
include::macros/header.txt

== View the page locally
You can render the page locally and check it out inside a web browser, though this won't be identical to
the way it renders in either GitHub or on the Spring website.

[source]
asciidoc README.asciidoc

Open README.html with your browser.

== How to keep your guide up to date
Once you've set up your guide's infrastructure as shown above, you'll get notified whenever changes are made to
the shared getting-started-base project. 

Basically, you just have to sync up to the latest batch of updates to getting-started-base, like this:

[source]
git checkout master
git pull --no-ff getting-started-base master


